export const REQUEST_DETAIL = 'REQUEST_DETAIL'
export const RECEIVE_DETAIL = 'RECEIVE_DETAIL'
export const REQUEST_EVENTS = 'REQUEST_EVENTS'
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS'
export const RECEIVE_EVENTS_FAILED = 'RECEIVE_EVENTS_FAILED'

export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const RECEIVE_SOURCES = 'RECEIVE_SOURCES';